version: '3'

services:

  feathers_chat_api:
    container_name: feathers_chat_api
    build: .
    volumes:
      - .:/home/feathers-chat
      - /home/feathers-chat/node_modules
    working_dir: /home/feathers-chat
    # ports:
      # - 3030:3030
    environment:
      - POSTGRES_HOST=feathers_chat_db
    depends_on:
      - feathers_chat_database
    env_file:
      - ./.env

  feathers_chat_database:
    container_name: feathers_chat_db
    image: postgres:15.1-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432